### ISSUE TITLE
Dimensions of trial variables

### ISSUE THREAD

**Issue by nmasse** [nmasse/Short-term-plasticity-RNN#4]
In trial_generators.py, let's make the variables inside trial_setup have fixed dimensions. If there are 4 receptive fields (or the task equivalent), than sample_index would have shape (1000,4). But if there's only one receptive field, the dimension is (1000,), which makes downstream analysis a bit of a pain. Let's always make this variable, and others like it, have dim = (1000,1).

**Comment by gdgrant** [comment]
That shouldn't be a hard fix - I'll add that in on my next push.   If I'm not mistaken, np.atleast_2d should work!

**Comment by nmasse** [comment]
Excellent! Maybe instead of functions like atleast_2d, let's just pre-allocate the exact size we want from the start.

**Comment by gdgrant** [comment]
I definitely like that idea.  At the moment, those particular setups are list-based (and then converted over), but can easily be switched over to numpy arrays.  I'll do that first thing tomorrow!
